import { promises as fs } from "node:fs";
import path from "node:path";

export const WORKFLOW_PATH = ".github/workflows/conclave.yml";
export const REWORK_WORKFLOW_PATH = ".github/workflows/conclave-rework.yml";
/**
 * Reusable workflow source — GitHub ref for the hosted review workflow.
 * Currently served from `seunghunbae-3svs/conclave-ai`; planned to move
 * to a dedicated `conclave-ai` org once the repo is transferred.
 *
 * The `v0.4` ref is a FLOATING tag — every release workflow run moves
 * it forward to the new main HEAD so existing installs auto-pick up
 * fixes without re-running `conclave init`. Bumping the major part
 * (e.g. `v0.5`) signals a breaking change to the workflow contract;
 * downstream installs would need to re-init to track it.
 */
export const REUSABLE_REF = "seunghunbae-3svs/conclave-ai/.github/workflows/review.yml@v0.4";
/**
 * v0.10 — separate ref for the rework (autofix) reusable workflow. Same
 * floating major-tag track as REUSABLE_REF so the release pipeline
 * moves them in lockstep. Kept as a distinct constant so a future
 * ref-bump could pin the two workflows independently if needed.
 */
export const REWORK_REUSABLE_REF =
  "seunghunbae-3svs/conclave-ai/.github/workflows/rework.yml@v0.4";

/**
 * The 3-line (effective) wrapper workflow per D7. Users DO NOT edit this
 * file — everything that matters (action versions, review logic, memory
 * persistence, telegram posting) lives in the reusable workflow we host.
 * `secrets: inherit` passes the user's own LLM keys through without
 * surfacing them. The header comment tells humans reading their own repo
 * exactly what's happening and where to look.
 */
export const WORKFLOW_CONTENT = `# Generated by \`conclave init\`. Do not edit — conclave updates via its reusable workflow.
# Source: https://github.com/${REUSABLE_REF.split("@")[0]!.replace(".github/workflows/review.yml", "")}
name: Conclave AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conclave:
    uses: ${REUSABLE_REF}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
`;

/**
 * v0.10 — consumer-side dispatcher for the autonomous rework loop.
 *
 * Listens for `repository_dispatch` of type `conclave-rework`, fired by
 * the central plane (apps/central-plane) whenever a review verdict
 * comes back as "rework" AND `cycle < max_cycles`. The dispatch payload
 * carries `pr_number`, `cycle`, and `max_cycles`; this file forwards
 * them into our reusable rework.yml which runs `conclave autofix`,
 * commits + pushes, and re-triggers review via the resulting
 * `pull_request: synchronize` event.
 *
 * Without this file the central plane fires the dispatch event but the
 * consumer repo has no listener — the loop never closes. Pre-v0.10
 * installs that miss this file will only get review (no autonomous
 * rework); they should re-run `conclave init --reconfigure` to pick it
 * up.
 */
export const REWORK_WORKFLOW_CONTENT = `# Generated by \`conclave init\`. Do not edit — conclave updates via its reusable workflow.
# v0.10 — consumer-side dispatcher for the autonomous rework loop.
# Source: https://github.com/${REWORK_REUSABLE_REF.split("@")[0]!.replace(".github/workflows/rework.yml", "")}
name: Conclave AI Rework

on:
  repository_dispatch:
    types: [conclave-rework]

jobs:
  rework:
    uses: ${REWORK_REUSABLE_REF}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
    with:
      pr-number: \${{ github.event.client_payload.pr_number }}
      cycle: \${{ github.event.client_payload.cycle }}
      max-cycles: \${{ github.event.client_payload.max_cycles }}
`;

export interface WriteWorkflowInput {
  cwd: string;
  force?: boolean;
}

export interface WriteWorkflowOutput {
  path: string;
  created: boolean;
  skipped: boolean;
}

export async function writeWorkflow(input: WriteWorkflowInput): Promise<WriteWorkflowOutput> {
  const target = path.join(input.cwd, WORKFLOW_PATH);
  const exists = await fs
    .access(target)
    .then(() => true)
    .catch(() => false);
  if (exists && !input.force) {
    return { path: target, created: false, skipped: true };
  }
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, WORKFLOW_CONTENT, "utf8");
  return { path: target, created: true, skipped: false };
}

/**
 * v0.10 — write the rework dispatcher workflow alongside the main
 * conclave.yml. Idempotent: existing files are preserved unless `force`
 * is set, mirroring `writeWorkflow`'s behaviour.
 */
export async function writeReworkWorkflow(
  input: WriteWorkflowInput,
): Promise<WriteWorkflowOutput> {
  const target = path.join(input.cwd, REWORK_WORKFLOW_PATH);
  const exists = await fs
    .access(target)
    .then(() => true)
    .catch(() => false);
  if (exists && !input.force) {
    return { path: target, created: false, skipped: true };
  }
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, REWORK_WORKFLOW_CONTENT, "utf8");
  return { path: target, created: true, skipped: false };
}
