import { promises as fs } from "node:fs";
import path from "node:path";

export const WORKFLOW_PATH = ".github/workflows/conclave.yml";
/**
 * Reusable workflow source — GitHub ref for the hosted review workflow.
 * Currently served from `seunghunbae-3svs/conclave-ai`; planned to move to
 * a dedicated `conclave-ai` org once the repo is transferred. When that
 * rename happens, change this one string and all new `conclave init` runs
 * pick up the new path. Existing installs continue to resolve the old
 * path until they re-run `conclave init --reconfigure`.
 */
export const REUSABLE_REF = "seunghunbae-3svs/conclave-ai/.github/workflows/review.yml@v0.4";

/**
 * The 3-line (effective) wrapper workflow per D7. Users DO NOT edit this
 * file — everything that matters (action versions, review logic, memory
 * persistence, telegram posting) lives in the reusable workflow we host.
 * `secrets: inherit` passes the user's own LLM keys through without
 * surfacing them. The header comment tells humans reading their own repo
 * exactly what's happening and where to look.
 */
export const WORKFLOW_CONTENT = `# Generated by \`conclave init\`. Do not edit — conclave updates via its reusable workflow.
# Source: https://github.com/${REUSABLE_REF.split("@")[0]!.replace(".github/workflows/review.yml", "")}
name: Conclave AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conclave:
    uses: ${REUSABLE_REF}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
`;

export interface WriteWorkflowInput {
  cwd: string;
  force?: boolean;
}

export interface WriteWorkflowOutput {
  path: string;
  created: boolean;
  skipped: boolean;
}

export async function writeWorkflow(input: WriteWorkflowInput): Promise<WriteWorkflowOutput> {
  const target = path.join(input.cwd, WORKFLOW_PATH);
  const exists = await fs
    .access(target)
    .then(() => true)
    .catch(() => false);
  if (exists && !input.force) {
    return { path: target, created: false, skipped: true };
  }
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, WORKFLOW_CONTENT, "utf8");
  return { path: target, created: true, skipped: false };
}
