import { promises as fs } from "node:fs";
import path from "node:path";

export const WORKFLOW_PATH = ".github/workflows/conclave.yml";
export const REWORK_WORKFLOW_PATH = ".github/workflows/conclave-rework.yml";
export const MERGE_WORKFLOW_PATH = ".github/workflows/conclave-merge.yml";
/**
 * Reusable workflow source — GitHub ref for the hosted review workflow.
 * Currently served from `seunghunbae-3svs/conclave-ai`; planned to move
 * to a dedicated `conclave-ai` org once the repo is transferred.
 *
 * The `v0.4` ref is a FLOATING tag — every release workflow run moves
 * it forward to the new main HEAD so existing installs auto-pick up
 * fixes without re-running `conclave init`. Bumping the major part
 * (e.g. `v0.5`) signals a breaking change to the workflow contract;
 * downstream installs would need to re-init to track it.
 */
export const REUSABLE_REF = "seunghunbae-3svs/conclave-ai/.github/workflows/review.yml@v0.4";
/**
 * v0.10 — separate ref for the rework (autofix) reusable workflow. Same
 * floating major-tag track as REUSABLE_REF so the release pipeline
 * moves them in lockstep. Kept as a distinct constant so a future
 * ref-bump could pin the two workflows independently if needed.
 */
export const REWORK_REUSABLE_REF =
  "seunghunbae-3svs/conclave-ai/.github/workflows/rework.yml@v0.4";
/**
 * v0.13.17 — separate ref for the merge reusable workflow. Same
 * floating major-tag track as REUSABLE_REF and REWORK_REUSABLE_REF.
 * Without this file consumers' merge dispatch does nothing and the
 * autonomy loop never delivers its terminal "✅ Merged" notification.
 */
export const MERGE_REUSABLE_REF =
  "seunghunbae-3svs/conclave-ai/.github/workflows/merge.yml@v0.4";

/**
 * The 3-line (effective) wrapper workflow per D7. Users DO NOT edit this
 * file — everything that matters (action versions, review logic, memory
 * persistence, telegram posting) lives in the reusable workflow we host.
 * `secrets: inherit` passes the user's own LLM keys through without
 * surfacing them. The header comment tells humans reading their own repo
 * exactly what's happening and where to look.
 */
export const WORKFLOW_CONTENT = `# Generated by \`conclave init\`. Do not edit — conclave updates via its reusable workflow.
# Source: https://github.com/${REUSABLE_REF.split("@")[0]!.replace(".github/workflows/review.yml", "")}
name: Conclave AI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conclave:
    uses: ${REUSABLE_REF}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
`;

/**
 * v0.10 — consumer-side dispatcher for the autonomous rework loop.
 *
 * Listens for `repository_dispatch` of type `conclave-rework`, fired by
 * the central plane (apps/central-plane) whenever a review verdict
 * comes back as "rework" AND `cycle < max_cycles`. The dispatch payload
 * carries `pr_number`, `cycle`, and `max_cycles`; this file forwards
 * them into our reusable rework.yml which runs `conclave autofix`,
 * commits + pushes, and re-triggers review via the resulting
 * `pull_request: synchronize` event.
 *
 * Without this file the central plane fires the dispatch event but the
 * consumer repo has no listener — the loop never closes. Pre-v0.10
 * installs that miss this file will only get review (no autonomous
 * rework); they should re-run `conclave init --reconfigure` to pick it
 * up.
 */
export const REWORK_WORKFLOW_CONTENT = `# Generated by \`conclave init\`. Do not edit — conclave updates via its reusable workflow.
# v0.10 — consumer-side dispatcher for the autonomous rework loop.
# Source: https://github.com/${REWORK_REUSABLE_REF.split("@")[0]!.replace(".github/workflows/rework.yml", "")}
name: Conclave AI Rework

on:
  repository_dispatch:
    types: [conclave-rework]

jobs:
  rework:
    uses: ${REWORK_REUSABLE_REF}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
    with:
      pr-number: \${{ github.event.client_payload.pr_number }}
      cycle: \${{ github.event.client_payload.cycle }}
      max-cycles: \${{ github.event.client_payload.max_cycles }}
`;

/**
 * v0.13.17 — consumer-side dispatcher for the autonomy loop's merge
 * leg. Listens for `repository_dispatch` of type `conclave-merge`,
 * fired by the central plane when the user clicks ✅ Merge & Push in
 * Telegram. Forwards into our reusable merge.yml which:
 *   1. resolves the PR number from the dispatch payload,
 *   2. merges the PR with `gh pr merge --squash --delete-branch`,
 *   3. POSTs /merge/notify on the central plane so a final
 *      "✅ Merged" message lands in Telegram (the loop-closure signal),
 *   4. records the outcome (best-effort).
 *
 * Without this file the merge dispatch lands but no listener catches
 * it, the PR never merges from the Telegram button, and Bae sees an
 * inert ✅ button. Live RC: eventbadge#32 had a v0.7-era inline
 * conclave-merge.yml that merged the PR but skipped the
 * notify+record-outcome handoff — the user-visible loop felt broken
 * even though the merge happened.
 */
export const MERGE_WORKFLOW_CONTENT = `# Generated by \`conclave init\`. Do not edit — conclave updates via its reusable workflow.
# v0.13.17 — consumer-side dispatcher for the autonomy loop's merge leg.
# Source: https://github.com/${MERGE_REUSABLE_REF.split("@")[0]!.replace(".github/workflows/merge.yml", "")}
name: Conclave AI Merge

on:
  repository_dispatch:
    types: [conclave-merge]

jobs:
  merge:
    uses: ${MERGE_REUSABLE_REF}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
`;

export interface WriteWorkflowInput {
  cwd: string;
  /**
   * Force overwrite even when the existing file has been
   * user-customised (no managed-header marker). Reserved for the
   * `conclave init --reconfigure` escape hatch.
   */
  force?: boolean;
}

/**
 * v0.13.18 — write outcome.
 *
 *   "created"   — file did not exist; wrote fresh.
 *   "migrated"  — file existed AND carried our managed-header marker
 *                 AND its content differed from the current template
 *                 → overwrote (we own this file). Live RC: PR #34
 *                 manually patched eventbadge's old-shape conclave-
 *                 merge.yml because `conclave init` couldn't tell
 *                 "this is a stale-template file we generated" from
 *                 "this is something the user wrote". Now it can.
 *   "skipped-current" — file matches the current template byte-for-byte;
 *                       no work needed.
 *   "skipped-customised" — file exists, lacks the managed-header
 *                          marker; treat as user-owned, leave alone.
 *                          --force overrides.
 */
export type WriteWorkflowStatus =
  | "created"
  | "migrated"
  | "skipped-current"
  | "skipped-customised";

export interface WriteWorkflowOutput {
  path: string;
  status: WriteWorkflowStatus;
  /** Compatibility with pre-v0.13.18 callers — true when the file was
   * NOT touched (skipped-current OR skipped-customised). */
  skipped: boolean;
  /** Compatibility — true when the file was newly created (NOT migrated). */
  created: boolean;
}

/**
 * Header marker we put on every workflow file we own. If a file
 * starts with this string we treat it as "ours to update"; if not,
 * we treat it as user-customised and leave alone (unless --force).
 *
 * Both content templates start with `# Generated by \`conclave init\`.`
 * so any of them is detectable by this single substring check.
 */
const MANAGED_HEADER_MARKER = "Generated by `conclave init`";

/**
 * Render a one-line status message for an init step. Centralised so
 * `conclave init` and any future consumer (test snapshots, dry-run
 * preview) format these consistently.
 */
export function formatWorkflowStatusLine(
  relativePath: string,
  status: WriteWorkflowStatus,
): string {
  switch (status) {
    case "created":
      return `• wrote:    ${relativePath} (new)\n`;
    case "migrated":
      return `• migrated: ${relativePath} (was an older managed template — auto-updated)\n`;
    case "skipped-current":
      return `• ok:       ${relativePath} (already up to date)\n`;
    case "skipped-customised":
      return `• keep:     ${relativePath} (user-customised — preserved; pass --reconfigure to overwrite)\n`;
  }
}

async function pathExists(p: string): Promise<boolean> {
  return fs
    .access(p)
    .then(() => true)
    .catch(() => false);
}

function isManagedFile(content: string): boolean {
  // Only check the first 200 chars — the marker is on line 1 of all
  // our templates and we don't want a deep scan.
  return content.slice(0, 200).includes(MANAGED_HEADER_MARKER);
}

/**
 * Single workhorse for write-or-migrate semantics. All three
 * `writeXxxWorkflow` functions delegate here so the migration logic
 * lives in exactly one place.
 */
async function writeOrMigrate(
  target: string,
  template: string,
  force: boolean,
): Promise<WriteWorkflowOutput> {
  const exists = await pathExists(target);
  if (!exists) {
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, template, "utf8");
    return { path: target, status: "created", skipped: false, created: true };
  }
  // File exists. Decide between skip-current / migrate / skip-customised / force-overwrite.
  let existing = "";
  try {
    existing = await fs.readFile(target, "utf8");
  } catch {
    // Read failure on an existing file is rare. Fall through to
    // overwrite under --force; otherwise treat as customised.
  }
  if (force) {
    await fs.writeFile(target, template, "utf8");
    // --force on an unchanged file still counts as "migrated" so the
    // user gets a clear "I overwrote it" log. Same effective result.
    return { path: target, status: "migrated", skipped: false, created: false };
  }
  if (existing === template) {
    return { path: target, status: "skipped-current", skipped: true, created: false };
  }
  if (isManagedFile(existing)) {
    // We own this file (we put the marker there). Old template →
    // migrate. This is the "auto-migration" path that closes H1 #1.
    await fs.writeFile(target, template, "utf8");
    return { path: target, status: "migrated", skipped: false, created: false };
  }
  // No marker → user-customised. Don't touch without --force.
  return { path: target, status: "skipped-customised", skipped: true, created: false };
}

export async function writeWorkflow(input: WriteWorkflowInput): Promise<WriteWorkflowOutput> {
  return writeOrMigrate(
    path.join(input.cwd, WORKFLOW_PATH),
    WORKFLOW_CONTENT,
    !!input.force,
  );
}

/**
 * v0.10 — write the rework dispatcher workflow alongside the main
 * conclave.yml. Idempotent: matches → skip; managed + stale →
 * auto-migrate; user-customised → preserve unless --force.
 */
export async function writeReworkWorkflow(
  input: WriteWorkflowInput,
): Promise<WriteWorkflowOutput> {
  return writeOrMigrate(
    path.join(input.cwd, REWORK_WORKFLOW_PATH),
    REWORK_WORKFLOW_CONTENT,
    !!input.force,
  );
}

/**
 * v0.13.17 — write the merge dispatcher workflow. Same migration
 * semantics as writeReworkWorkflow.
 */
export async function writeMergeWorkflow(
  input: WriteWorkflowInput,
): Promise<WriteWorkflowOutput> {
  return writeOrMigrate(
    path.join(input.cwd, MERGE_WORKFLOW_PATH),
    MERGE_WORKFLOW_CONTENT,
    !!input.force,
  );
}
